# Set versions here ----

# TileDB
{% set version_tiledb = "2.18.4" %}
{% set git_rev_tiledb = "2.18.4" %}

# TileDB-Py
{% set version_tiledb_py = "0.24.0" %}
{% set git_rev_tiledb_py = "0.24.0" %}

# TileDB-R
{% set version_tiledb_r = "0.22.0" %}
{% set git_rev_tiledb_r = "0.22.0" %}

# TileDB-VCF
{% set version_tiledb_vcf = "0.27.1" %}
{% set git_rev_tiledb_vcf = "0.27.1" %}

# TileDB-SOMA
{% set version_tiledb_soma = "1.6.2" %}
{% set git_rev_tiledb_soma = "1.6.2" %}

package:
  # These are just placeholders. Each separate output defines its name and
  # version
  name: tiledb-stack
  version: 0.0.0.0

source:
  - git_url: https://github.com/TileDB-Inc/TileDB.git
    git_rev:  {{ git_rev_tiledb }}
    folder: TileDB/
  - git_url: https://github.com/TileDB-Inc/TileDB-Py.git
    git_rev: {{ git_rev_tiledb_py }}
    folder: TileDB-Py/
  - git_url: https://github.com/TileDB-Inc/TileDB-R.git
    git_rev: {{ git_rev_tiledb_r }}
    folder: TileDB-R/
  - git_url: https://github.com/TileDB-Inc/TileDB-VCF.git
    git_rev: {{ git_rev_tiledb_vcf }}
    folder: TileDB-VCF/
  - git_url: https://github.com/single-cell-data/TileDB-SOMA.git
    git_rev: {{ git_rev_tiledb_soma }}
    folder: TileDB-SOMA/

outputs:
  - name: tiledb
    version: {{ version_tiledb }}
    script: build-tiledb.sh
    build:
      number: 0
      run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=tiledb
        - {{ pin_subpackage('tiledb', max_pin='x.x') }}
    requirements:
      build:
        - make
        - cmake
        - pkg-config
        - {{ compiler('cxx') }}
      host:
        - azure-core-cpp <1.11
        - azure-storage-common-cpp
        - azure-storage-blobs-cpp
        - bzip2
        - libcurl
        - lz4-c
        - google-cloud-cpp
        - libabseil
        - openssl
        - zlib
        - zstd
        - libxml2
    test:
      files:
        - test-tiledb-linking.sh
        - link_test_src/
      requires:
        - {{ compiler('cxx') }}
        - cmake
        - libarrow
        - make
      commands:
        - test -e $PREFIX/include/tiledb/tiledb.h
        - test -e $PREFIX/include/tiledb/tiledb
        - test -e $PREFIX/lib/libtiledb$SHLIB_EXT
        - bash test-tiledb-linking.sh
    about:
      home: http://tiledb.io
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB sparse and dense multi-dimensional array data management
      description: |
        TileDB is an efficient multi-dimensional array management system which introduces
        a novel on-disk format that can effectively store dense and sparse array data with
        support for fast updates and reads. It features excellent compression, and an efficient
        parallel I/O system with high scalability.
      doc_url: http://docs.tiledb.io
      dev_url: https://github.com/TileDB-Inc/TileDB
  - name: tiledb-py
    version: {{ version_tiledb_py }}
    script: build-tiledb-py.sh
    build:
      number: 0
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - pip
        - wheel
        - setuptools
        - setuptools_scm
        - python
        - cython <3.0
        - numpy
        - pybind11 <2.11
        - {{ pin_subpackage('tiledb', exact=True) }}
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - packaging
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      requires:
        - hypothesis
        - pyarrow
        - pytest
        - pandas
        - psutil
      imports:
        - tiledb
      source_files:
        - TileDB-Py/tiledb/tests/
      commands:
        - python -c "import tiledb; tiledb.libtiledb.version()"
        - python -c "import tiledb; assert tiledb.VFS().supports('s3')"
        - cd TileDB-Py && pytest -v --ignore-glob='*_examples.py' --ignore-glob='*_dask.py'
    about:
      home: http://tiledb.io
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Python interface to the TileDB sparse and dense multi-dimensional array storage manager
      description: |
        TileDB-Py is the python interface to the TileDB array storage manager.
        TileDB  is an efficient multi-dimensional array management system which introduces
        a novel on-disk format that can store dense and sparse array data with
        support for fast reads and updates and reads. It features excellent compression, and an efficient
        parallel I/O system with high scalability.
      doc_url: https://api-reference.tiledb.io/python-api.html
      dev_url: https://github.com/TileDB-Inc/TileDB-Py
  - name: r-tiledb
    version: {{ version_tiledb_r }}
    script: build-tiledb-r.sh
    build:
      number: 0
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
        - make
      host:
        - r-base
        - {{ pin_subpackage('tiledb', exact=True) }}
        - r-rcpp >=1.0.8
        - r-rcppspdlog
        - r-nanotime
        - r-spdl
        - r-rcppint64
      run:
        - r-base
        - r-nanotime
        - r-spdl
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      requires:
        - r-tinytest
        - r-nycflights13
        - r-palmerpenguins
        - r-data.table
      commands:
        - Rscript -e 'tinytest::test_package("tiledb")'
    about:
      home: https://www.tiledb.com
      license: MIT
      license_file:
        - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
        - LICENSE
      summary: R interface to the TileDB array storage manager
      description: |
        TileDB is a highly-parallelized, cloud native array storage engine.
      doc_url: https://docs.tiledb.com/developer/
      dev_url: https://github.com/TileDB-Inc/TileDB-R
  - name: libtiledbvcf
    version: {{ version_tiledb_vcf }}
    script: build-tiledb-vcf.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
      host:
        - htslib >=1.15
        - {{ pin_subpackage('tiledb', exact=True) }}
      run:
        - htslib >=1.15
        - {{ pin_subpackage('tiledb', exact=True) }}
    test:
      files:
        - test-tiledb-vcf-cli.sh
      commands:
        - tiledbvcf version
        # verify libhts is linked
        - ldd ${PREFIX}/lib/libtiledbvcf.so | grep libhts
        # verify libdeflate is linked to libhts
        - ldd ${PREFIX}/lib/libhts.so.* | grep libdeflate
        - tiledbvcf create --uri /tmp/test-tiledbvcf-conda
        - bash test-tiledb-vcf-cli.sh
  - name: tiledbvcf-py
    version: {{ version_tiledb_vcf }}
    script: build-tiledb-vcf-py.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - numpy
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - pyarrow  {{ pyarrow }}
        - pybind11 >=2.5
        - wheel >=0.30
        - setuptools >=18.0
        - setuptools_scm 6.0.1
        - setuptools_scm_git_archive
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbvcf', exact=True) }}
        - python
        - {{ pin_compatible('pyarrow', max_pin='x') }}
        - pandas
    imports:
      - tiledbvcf
    test:
      requires:
        - jupyter
        - pyarrow
        - tensorflow
      files:
        - test-tiledb-vcf-api.py
      commands:
        - python -c "import tiledbvcf; tiledbvcf.version"
        - python test-tiledb-vcf-api.py
  - name: libtiledbsoma
    version: {{ version_tiledb_soma }}
    script: build-tiledb-soma.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - git
        - cmake
        - make
      host:
        - {{ pin_subpackage('tiledb', exact=True) }}
        - spdlog
        - fmt
      run:
        - {{ pin_subpackage('tiledb', exact=True) }}
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA C++ library
      description: >-
        SOMA - for "Stack Of Matrices, Annotated" - is a flexible, extensible,
        and open-source API enabling access to data in a variety of formats. The
        driving use case of SOMA is for single-cell data in the form of
        annotated matrices where observations are frequently cells and features
        are genes, proteins, or genomic regions.
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA
  - name: tiledbsoma-py
    version: {{ version_tiledb_soma }}
    script: build-tiledb-soma-py.sh
    build:
    requirements:
      build:
        - {{ compiler('cxx') }}
      host:
        - python
        - pip
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pybind11
        - setuptools
        - setuptools_scm
        - wheel
        - numpy
        - pyarrow {{ pyarrow }}
        - pyarrow-hotfix
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16', upper_bound='1.24') }}
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - pandas
        - pyarrow {{ pyarrow }}
        - pyarrow-hotfix
        - python
        - scipy
        - anndata <0.10
        - {{ pin_subpackage('tiledb-py', exact=True) }}
        - typing-extensions >=4.1
        - numba
        - attrs >=22.2
        - somacore >=1.0.6
        - scanpy 1.9.*
    test:
      requires:
        - jupyter
        - pyarrow
        - tensorflow
      imports:
        - tiledbsoma
      commands:
        - python -c "import tiledbsoma; print(tiledbsoma.pytiledbsoma.version())"
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: TileDB-SOMA Python API
      description: Python API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/python
  - name: r-tiledbsoma
    version: {{ version_tiledb_soma }}
    script: build-tiledb-soma-r.sh
    build:
      rpaths:
        - lib/R/lib/
        - lib/
    requirements:
      build:
        - {{ compiler('cxx') }}
        - pkg-config
      host:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - r-rcppint64
        - {{ pin_subpackage('r-tiledb', exact=True) }}
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
      run:
        - {{ pin_subpackage('libtiledbsoma', exact=True) }}
        - r-base
        - r-r6
        - r-matrix
        - r-bit64
        - {{ pin_subpackage('r-tiledb', exact=True) }}
        - r-arrow
        - r-fs
        - r-glue
        - r-urltools
        - r-rcpp
        - r-dplyr
        - r-data.table
        - r-spdl
        - r-rlang
    test:
      commands:
        - $R -e "library('tiledbsoma')"
        - $R -e "tiledbsoma::show_package_versions()"
        - "ldd $PREFIX/lib/R/library/tiledbsoma/libs/tiledbsoma.so | grep -e libR -e libtiledb"
    about:
      home: http://tiledb.com
      license: MIT
      license_family: MIT
      license_file:
        - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
        - TileDB-SOMA/apis/r/LICENSE
      summary: TileDB-SOMA R API
      description: R API for efficient storage and retrieval of single-cell data using TileDB
      doc_url: https://docs.tiledb.com/
      dev_url: https://github.com/single-cell-data/TileDB-SOMA/tree/main/apis/r

about:
  home: http://tiledb.io
  license: MIT
  license_family: MIT
  summary: TileDB stack to deploy to TileDB Cloud
  description: |
    Special set of linux binaries for easy deployment
  doc_url: http://docs.tiledb.io
  dev_url: https://github.com/TileDB-Inc/TileDB

extra:
  recipe-maintainers:
    - ihnorton
    - jdblischak
    - shelnutt2
